[package]
name = "rusty_xmas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rayon = "1.5.3"
reqwest = { version = "0.11", features = ["blocking", "cookies"] }
